// <auto-generated />
using System;
using DAL.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.EF.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Domain.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendshipId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendshipId = 2
                        },
                        new
                        {
                            Id = 3,
                            FriendshipId = 4
                        },
                        new
                        {
                            Id = 4,
                            FriendshipId = 3
                        },
                        new
                        {
                            Id = 5,
                            FriendshipId = 7
                        });
                });

            modelBuilder.Entity("DAL.Domain.Friendship", b =>
                {
                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("FriendId", "UserId");

                    b.HasIndex("ChatId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            FriendId = 3,
                            UserId = 1,
                            ChatId = 1,
                            Id = 1
                        },
                        new
                        {
                            FriendId = 4,
                            UserId = 1,
                            ChatId = 2,
                            Id = 2
                        },
                        new
                        {
                            FriendId = 3,
                            UserId = 2,
                            ChatId = 4,
                            Id = 3
                        },
                        new
                        {
                            FriendId = 5,
                            UserId = 2,
                            ChatId = 3,
                            Id = 4
                        },
                        new
                        {
                            FriendId = 4,
                            UserId = 3,
                            ChatId = 5,
                            Id = 7
                        });
                });

            modelBuilder.Entity("DAL.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DAL.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserIdentityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "In love with math and computing. Do you dare to complete? DM me then",
                            Age = 25,
                            City = "London",
                            Country = "England",
                            Email = "ada.love@gmail.com",
                            FirstName = "Ada",
                            LastName = "Lovelace",
                            PhoneNumber = "+380 44 446 6356",
                            University = "Oxford",
                            UserName = "ada.love"
                        },
                        new
                        {
                            Id = 2,
                            AboutMe = "Shy fancy boy",
                            Age = 18,
                            City = "New York",
                            Country = "USA",
                            Email = "tim@gmail.com",
                            FirstName = "Tim",
                            LastName = "Delaney",
                            PhoneNumber = "+380 44 538 6141",
                            University = "Grand Army",
                            UserName = "timmy"
                        },
                        new
                        {
                            Id = 3,
                            AboutMe = "I live in two worlds, one of them is the world of books",
                            Age = 23,
                            City = "Starts Hollow",
                            Country = "USA",
                            Email = "rory.gilmore@gmail.com",
                            FirstName = "Lorelai",
                            LastName = "Gilmore",
                            PhoneNumber = "+380 44 193 0152",
                            University = "Harvard",
                            UserName = "rory"
                        },
                        new
                        {
                            Id = 4,
                            AboutMe = "I run the dinner in the downtown, come only hungry",
                            Age = 45,
                            City = "Vinnytsia",
                            Country = "Ukraine",
                            Email = "luke.danes@gmail.com",
                            FirstName = "Luke",
                            LastName = "Danes",
                            PhoneNumber = "+380 44 038 0434",
                            UserName = "luke`s"
                        },
                        new
                        {
                            Id = 5,
                            AboutMe = "In love with dancing and music, protecting girls` rights",
                            Age = 17,
                            City = "New York",
                            Country = "USA",
                            Email = "del.marco@gmail.com",
                            FirstName = "Joey",
                            LastName = "Del Marco",
                            PhoneNumber = "+380 44 177 6783",
                            University = "NYU",
                            UserName = "jojo"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Friendship", b =>
                {
                    b.HasOne("DAL.Domain.Chat", null)
                        .WithMany("Friendships")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.User", "Friend")
                        .WithMany("Friendships")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Domain.Message", b =>
                {
                    b.HasOne("DAL.Domain.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Domain.User", b =>
                {
                    b.HasOne("DAL.Domain.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
